In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("spam.csv")
df.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [ ]:
df['spam'] = df['Category'].apply(lambda x: 1 if x =='spam' else 0)

In [ ]:
df.shape

(5572, 3)

In [ ]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

Train test split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size=0.2)

In [ ]:
X_train.shape

(4457,)

In [ ]:
X_test.shape

(1115,)

In [ ]:
type(X_train)

pandas.core.series.Series

In [ ]:
X_train[:4]

1266    Im in inperialmusic listening2the weirdest tra...
1574    SMS AUCTION - A BRAND NEW Nokia 7250 is up 4 a...
58                                 Tell where you reached
5322                       Thanks, I'll keep that in mind
Name: Message, dtype: object

In [ ]:
type(y_train)

pandas.core.series.Series

In [ ]:
y_train[:4]

1266    0
1574    1
58      0
5322    0
Name: spam, dtype: int64

In [ ]:
type(X_train.values)

numpy.ndarray

Create bag of words representation using CountVectorizer

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)
X_train_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59391 stored elements and shape (4457, 7730)>

In [ ]:
X_train_cv.toarray()[:2][0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
X_train_cv.shape

(4457, 7730)

In [ ]:
v.get_feature_names_out()[1771]

'checkmate'

In [ ]:
v.vocabulary_

{'im': 3624,
 'in': 3648,
 'inperialmusic': 3692,
 'listening2the': 4149,
 'weirdest': 7436,
 'track': 6999,
 'ever': 2682,
 'by': 1603,
 'leafcutter': 4057,
 'john': 3841,
 'sounds': 6334,
 'like': 4113,
 'insects': 3695,
 'being': 1322,
 'molested': 4563,
 'someone': 6290,
 'plumbing': 5245,
 'remixed': 5683,
 'evil': 2695,
 'men': 4445,
 'on': 4919,
 'acid': 791,
 'sms': 6253,
 'auction': 1151,
 'brand': 1496,
 'new': 4749,
 'nokia': 4792,
 '7250': 607,
 'is': 3753,
 'up': 7173,
 'today': 6932,
 'free': 2993,
 'join': 3842,
 'take': 6681,
 'part': 5074,
 'txt': 7087,
 'to': 6927,
 '86021': 683,
 'now': 4830,
 'hg': 3432,
 'suite342': 6578,
 '2lands': 396,
 'row': 5814,
 'w1j6hl': 7325,
 'tell': 6746,
 'where': 7476,
 'you': 7691,
 'reached': 5578,
 'thanks': 6795,
 'll': 4163,
 'keep': 3910,
 'that': 6802,
 'mind': 4487,
 'will': 7508,
 'reach': 5576,
 'office': 4888,
 'around': 1079,
 'lt': 4249,
 'decimal': 2219,
 'gt': 3270,
 'amp': 953,
 'my': 4664,
 'mobile': 4545,
 'have': 336

In [ ]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
np.where(X_train_np[0]!=0)

(array([ 791, 1322, 1603, 2682, 2695, 3624, 3648, 3692, 3695, 3841, 4057,
        4113, 4149, 4445, 4563, 4919, 5245, 5683, 6290, 6334, 6999, 7436]),)

In [ ]:
X_train[:4][1579]

KeyError: 1579